#!/usr/bin/env python3
"""Export conversation from JSONL to readable text format."""

import json
import sys
from datetime import datetime

def format_content(content):
    """Clean up content by removing HTML tags."""
    if not content:
        return ""
    # Remove various command tags
    content = content.replace('<local-command-caveat>Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages or otherwise consider them in your response unless the user explicitly asks you to.</local-command-caveat>', '')
    content = content.replace('<command-name>/clear</command-name>', '')
    content = content.replace('<command-message>clear</command-message>', '')
    content = content.replace('<command-args></command-args>', '')
    # Clean up extra whitespace
    content = content.strip()
    return content

def parse_timestamp(ts):
    """Parse ISO timestamp."""
    try:
        dt = datetime.fromisoformat(ts.replace('Z', '+00:00'))
        return dt.strftime('%Y-%m-%d %H:%M:%S')
    except:
        return ts

def main():
    input_file = r"C:\Users\A\.claude\projects\C--Users-A--claude-PageIndex\87518490-ce14-4727-a130-b1a613119a6c.jsonl"
    output_file = r"C:\Users\A\.claude\KINXKit\CONVERSATION_EXPORT.txt"

    conversation = []

    with open(input_file, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                data = json.loads(line)

                # Skip metadata and system messages
                if data.get('type') == 'file-history-snapshot':
                    continue
                if data.get('isMeta'):
                    continue
                if data.get('subtype') == 'local_command':
                    continue

                # Extract message content
                msg_type = data.get('type', 'unknown')
                timestamp = parse_timestamp(data.get('timestamp', ''))

                if msg_type == 'user':
                    message = data.get('message', {})
                    content = message.get('content', '')
                    content = format_content(content)
                    if content:
                        conversation.append({
                            'type': 'USER',
                            'time': timestamp,
                            'content': content
                        })

                elif msg_type == 'assistant':
                    message = data.get('message', {})
                    content = message.get('content', '')
                    if content and content.strip():
                        conversation.append({
                            'type': 'ASSISTANT',
                            'time': timestamp,
                            'content': content
                        })

            except json.JSONDecodeError:
                continue
            except Exception as e:
                print(f"Error processing line: {e}", file=sys.stderr)
                continue

    # Write formatted output
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("=" * 80 + "\n")
        f.write("KINXKit 项目 - 完整对话记录导出\n")
        f.write(f"导出时间: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"对话条数: {len(conversation)}\n")
        f.write("=" * 80 + "\n\n")

        for i, item in enumerate(conversation, 1):
            separator = "=" * 80
            f.write(f"{separator}\n")
            f.write(f"[{i}] {item['type']} - {item['time']}\n")
            f.write(f"{separator}\n")
            f.write(f"{item['content']}\n\n")

    print(f"✅ 导出完成！")
    print(f"📄 输出文件: {output_file}")
    print(f"📊 共导出 {len(conversation)} 条对话")

if __name__ == '__main__':
    main()
