/**
 * 创建项目命令
 */

import { Command } from 'commander';
import ora from 'ora';
import inquirer from 'inquirer';
import { classifier } from '../nlp/classifier.js';
import { detector } from '../core/detector.js';
import { generator } from '../core/generator.js';
import { ProjectType, GenerateOptions } from '../types.js';
import {
  showWelcome,
  showEnvironmentInfo,
  showProjectTypeOptions,
  showTechStackRecommendation,
  showConfigConfirmation
} from '../prompt/welcome.js';
import { logger } from '../utils/logger.js';

/**
 * 创建项目命令
 */
export const createCommand = new Command('create')
  .description('创建新项目 (或使用 kinx 直接启动向导)')
  .argument('[name]', '项目名称（可选）', {
    default: ''
  })
  .action(async (name) => {
    try {
      // 1. 显示欢迎信息
      showWelcome();

      // 2. 环境检测
      const spinner = ora('检测环境...').start();
      const envInfo = await detector.detect();
      spinner.succeed('环境检测完成');

      // 3. 显示环境信息
      await showEnvironmentInfo(envInfo);

      // 4. 获取用户输入
      let projectName = name;

      if (!projectName) {
        const answers = await inquirer.prompt([
          {
            type: 'input',
            name: 'name',
            message: '📦 请输入项目名称:',
            default: 'my-project',
            validate: (input: string) => {
              if (!input || input.trim().length === 0) {
                return '项目名称不能为空';
              }
              if (!/^[a-z0-9-]+$/.test(input)) {
                return '项目名称只能包含小写字母、数字和连字符';
              }
              return true;
            }
          }
        ]);
        projectName = answers.name;
      }

      // 5. 项目类型选择
      showProjectTypeOptions();
      const typeAnswer = await inquirer.prompt([
        {
          type: 'list',
          name: 'type',
          message: '选择项目类型:',
          choices: [
            { name: '网站/网页应用', value: 'web_app' },
            { name: 'API/后端服务', value: 'api_service' },
            { name: 'AI/聊天机器人', value: 'ai_chatbot' },
            { name: '工具/脚本', value: 'utility' },
            { name: '直接描述我的想法', value: 'custom' }
          ]
        }
      ]);

      // 6. 如果选择直接描述，进行意图分析
      let projectType = typeAnswer.type;
      if (projectType === 'custom') {
        const customAnswer = await inquirer.prompt([
          {
            type: 'input',
            name: 'description',
            message: '💬 请描述你的项目想法:'
          }
        ]);

        const { type, stack } = await classifier.analyze(customAnswer.description, envInfo);
        projectType = type;

        showTechStackRecommendation(stack);
      } else {
        // 使用推荐的技术栈
        const stack = classifier.recommend(projectType as any, envInfo.cuda?.available);
        showTechStackRecommendation({ type: projectType, ...stack });
      }

      // 7. 配置确认
      const config = {
        name: projectName,
        type: projectType,
        path: `./${projectName}`,
        techStack: classifier.recommend(projectType as any, envInfo.cuda?.available),
        createGitHub: false,
        useDocker: true
      };

      showConfigConfirmation(config);

      // 8. 最终确认
      const confirm = await inquirer.prompt([
        {
          type: 'confirm',
          name: 'confirm',
          message: '确认创建项目?',
          default: true
        }
      ]);

      if (!confirm.confirm) {
        logger.info('已取消');
        return;
      }

      // 9. 开始创建项目
      logger.info('开始创建项目...');

      try {
        // 准备生成选项
        const generateOptions: GenerateOptions = {
          name: config.name,
          path: config.path,
          description: `${config.name} - Auto-generated by KINXKit`,
          techStack: config.techStack,
          overwrite: false
        };

        // 调用生成器创建项目
        await generator.generate(config.type as ProjectType, generateOptions);

        logger.success('项目创建成功！');
        logger.blank();
        logger.info('下一步:');
        logger.kv('1.', `cd ${config.name}`);
        logger.kv('2.', '查看 README.md 了解更多');
        logger.kv('3.', '运行 npm install 或 pip install -r requirements.txt');
        logger.blank();

      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : String(error);
        logger.error('项目创建失败', { error: errorMessage });
        logger.info('请检查错误信息并重试');
        process.exit(1);
      }

    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      logger.error('创建项目失败', { error: errorMessage });
      process.exit(1);
    }
  });
